### PR TITLE
Change the main language to TypeScript

### PR DESCRIPTION
**Pull request by KashEight**
# Overview

Replace the code from JavaScript(js) to TypeScript(ts).

# Roadmap/Checklist

These are the checklist to replace:

- [x] Setup ts environment
- [x] Add/Setup webpack/vite to transpile
- [x] Rewrite js files to ts
- [x] Refactoring codes for ts
- [x] Build and check booting correctly

# Optional Roadmap/Checklist

These are optional, but help developing, I think.

- [x] Add linters such as eslint, prettier
- [ ] Consider default package manager such as yarn, pnpm
- [ ] Add features not implemented

# Note

This is still WIP, so I send this PR as Draft.

### CODE REVIEW

**Comment by KashEight** [comment]
good sign :)

image

**Comment by KashEight** [comment]
I would open this PR when I had finished refactoring

**Comment by KashEight** [comment]
Refactoring is not completed due to a lot of changes I have to do :(
I would open this after I fix critical rendering issues.

**Comment by KashEight** [comment]
I forget that I should mention this PR when I opened @florensie

**Comment by florensie** [comment]
Thanks! I'll take a look later.

**Review by florensie — APPROVED** [review]
Looks great thanks! Sorry it took so long.

**Pull request merged**
